drop table if exists tmc_id_2019;
create table tmc_id_2019 (

tmc varchar(50),
road varchar(50),
direction varchar(50),
intersection varchar(50),
state varchar(5),
county varchar(10),
zip numeric,
start_latitude numeric,
start_longitude numeric,
end_latitude numeric,
end_longitude numeric,
miles numeric,
road_order numeric,
timezone_name varchar(50),
type varchar(9),
country varchar(5),
tmclinear int,
frc int,
border_set varchar(10),
f_system int,
urban_code int,
faciltype int,
structype int,
thrulanes int,
route_numb int,
route_sign int,
route_qual int,
altrtename varchar(10),
aadt numeric,
aadt_singl numeric,
aadt_combi numeric,
nhs int,
nhs_pct numeric,
strhnt_typ varchar(9),
strhnt_pct numeric,
truck varchar(9),
isprimary varchar(9),
active_start_date timestamptz,
active_end_date timestamptz,
thrulanes_unidir numeric,
aadt_unidir numeric,
aadt_singl_unidir numeric,
aadt_combi_unidir numeric
);
\copy tmc_id_2019 from program 'unzip -p /home/fullerm/repos/npmrds/downloads/2019/passenger/lmw_2019_inrix_passenger_seconds_nonull_10min.zip TMC_Identification.csv' with (format csv, header);
